## 들어가며

무언가 잘못될 가능성은 늘 존재한다. 잘못되면 바로 잡을 책임은 바로 우리 프로그래머에게 있다.

오류 처리 코드로 인해 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다.



## 오류 코드보다 예외를 사용하라

오류가 발생하면 `오류 코드` 로 처리하는 것 보다 `예외` 를 던지는 편이 낫다.

```java
/* Bad */
public class DeviceController {
  ...
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    // Check the state of the device
    if (handle != DeviceHandle.INVALID) {
      // Save the device status to the record field
      retrieveDeviceRecord(handle);
      // If not suspended, shut down
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log("Device suspended. Unable to shut down");
      }
    } else {
      logger.log("Invalid handle for: " + DEV1.toString());
    }
  }
  ...
}
```



```java
/* Good */
public class DeviceController {
  ...
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }
    
  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);
    pauseDevice(handle); 
    clearDeviceWorkQueue(handle); 
    closeDevice(handle);
  }
  
  private DeviceHandle getHandle(DeviceID id) {
    ...
    throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    ...
  }
  ...
}
```

오류를 체크하는 로직과 비즈니스 로직에 대한 알고리즘 부분을 분리함으로써, 코드를 깨끗하게 정리할 수 있다.



## Try-Catch-Finally 문부터 작성하라

어떤 면에서 `try` 블록은 트랜잭션과 비슷하다. `try` 블록에서 무슨 일이 생기든지 `catch` 블록은 프로그램의 상태를 일관성 있게 유지해야 한다. 그러므로 예외가 발생할 코드를 짤 때는 `try-catch-finally` 문으로 시작하는 편이 낫다. 그러면 `try` 블록에서 무슨 일이 생기든지 호출자가 기대하는 상태를 정의하기 쉬워진다.

다음은 파일이 없으면 예외를 던지는지 알아보는 단위 테스트이다.

```java
@Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }
  
  public List<RecordedGrip> retrieveSection(String sectionName) {
    // 실제로 구현할 때까지 비어있는 더미를 반환한다.
    return new ArrayList<RecordedGrip>();
  }
```

그런데 코드가 예외를 던지지 않으므로 단위 테스트는 실패한다. 일부러 잘못된 파일 접근을 시도하게 구현을 변경해보자.

```java
 public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
      throw new StorageException("retrieval error", e);
    }
  return new ArrayList<RecordedGrip>();
}
```

코드가 예외를 던지므로 작성한 테스트 케이스가 성공한다. 

```java
// 리팩터링: 예외 유형을 좁혀 정확한 예외를 잡아낼 수 있도록 코드를 수정
 public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName);
      // 오류나 예외가 전혀 발생하지 않는 로직을 추가
      // 이로써 하나의 트랜잭션으로 동작 가능
      stream.close();
    } catch (FileNotFoundException e) {
      throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
  }
```

먼저 강제로 예외를 일으키는 테스트 케이스를 작성한 후 테스트를 통과하게 코드를 작성하는 방법을 권장한다. 그러면 자연스럽게 `try` 블록의 트랜잭션 범위부터 구현하게 되므로 범위 내에서 트랜잭션 본질을 유지하기 쉬워진다.



## 미확인(unchecked) 예외를 사용하라

자바 프로그래머들은 확인된(checked) 예외의 장단점을 놓고 논쟁을 벌여왔다. `C# C++ Python Ruby` 는 확인된 예외를 지원하지 않지만, 안정적인 소프트웨어를 구현하기에 무리가 없다. 

자바의 첫 버전이 확인된 예외를 선보였던 당시는 확인된 예외가 멋진 아이디어로 여겨졌다. 프로그래머는 확인된 오류가 치르는 비용에 상응하는 이익을 제공하는지 철처하게 따져봐야 한다.

* 확인된 예외는 `OCP | Open Close Principle` 를 위반
  * 하위 함수가 던지는 예외가 달라진다면 상위 함수들의 수정이 필요
    * 함수의 선언부에 `throws` 를 추가해야하는 문제
    * `throws` 경로에 위치하는 모든 함수가 최하위 함수에서 던지는 예외를 알아야 하므로 캡슐화가 위배
* 필요에 의하면 확인된 예외를 사용해야 하지만, 득보다 실이 큼
  * 의존성에 의한 비용 > 확인된 예외 처리로 인한 이익 (손해 > 이익)
    * 의존성에 의해 상위 호출 함수들을 수정하는 것은 정교한 예외 처리를 하는 것 보다 손해
    * 던지는 예외 하나 고쳤다고 상위 함수들을 모두 수정하는 것은 번거로운 일



* `미확인 예외`
  * `RuntimeException` 에 포함된 예외를 의미
* 컴파일 시에는 문제 없지만 실행 중에 발생하는 예외를 의미



## 예외에 의미를 제공하라

`오류 메시지` 에 정보를 담아 예외와 함께 던진다. `실패한 연산 이름` 과 `실패 유형` 도 함께 언급하도록 한다. `catch` 블록에서 오류를 기록하도록 충분한 정보를 넘겨준다.



## 호출자를 고려해 예외 클래스를 정의하라

```java
	/* Bad */

  ACMEPort port = new ACMEPort(12);
  try {
    port.open();
  } catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
  } catch (ATM1212UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock exception", e);
  } catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception");
  } finally {
    ...
  }
```

위의 경우는 예외에 대응하는 방식이 예외 유형과 무관하게 거의 동일하다. 호출하는 라이브러리 API를 감싸면서 예외 유형 하나를 반환하면 된다.

```java
	/* Good */
  
  LocalPort port = new LocalPort(12);
  try {
    port.open();
  } catch (PortDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
  } finally {
    ...
  }
  
  public class LocalPort {
    private ACMEPort innerPort;
    public LocalPort(int portNumber) {
      innerPort = new ACMEPort(portNumber);
    }
    
    public void open() {
      try {
        innerPort.open();
      } catch (DeviceResponseException e) {
        throw new PortDeviceFailure(e);
      } catch (ATM1212UnlockedException e) {
        throw new PortDeviceFailure(e);
      } catch (GMXError e) {
        throw new PortDeviceFailure(e);
      }
    }
    ...
  }
```

외부 API를 감싸면 외부 라이브러리와 프로그램 사이의 의존성이 크게 줄어든다. 뿐만아니라, 특정 업체가 API를 설계한 방식에 발목 잡히지 않는다. 위 예제에서는 디바이스 실패를 표현하는 `예외 유형 하나를 정의` 했는데, 그랬더니 코드가 훨씬 깨끗해졌다.



## 정상 흐름을 정의하라

때로는 코드의 흐름에서 예외 처리로 인한 중단이 적합하지 않은 때도 있다.

`식비를 비용으로 청구했다면 직원이 청구한 식비를 총계에 더한다. `

`식비를 비용으로 청구하지 않았다면 일일 기본 식비를 총계에 더한다`

```java
  /* Bad */

  try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
  } catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
  }
```

특수 상항을 처리할 필요가 없다면 더 좋지 않을까?

```java
	/* Good */

  MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
  m_total += expenses.getTotal();
    
  public class PerDiemMealExpenses implements MealExpenses {
    public int getTotal() {
      // 일일 기본 식비를 반환한다.
    }
  }
```

`ExpenseReportDAO` 의 `getMeals()` 함수에서 이에 대한 예외를 처리하여 로직을 수행할 수 있도록 수정했다.



이를 `특수 사례 패턴 | SPECIAL CASE PATTERN` 이라 부른다. 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식이다. 그러면 클라이언트 코드가 예외적인 상황을 처리할 필요가 없어진다. 클래스나 객체가 예외적인 상황을 `캡슐화` 해서 처리하기 때문이다.



## NULL을 반환하지 마라

`NULL` 을 반환하는 습관으로 인해 오류를 유발하는 경우가 흔하다. `NULL` 을 반환하는 코드는 일거리를 늘릴 뿐만 아니라 호출자에게 문제를 떠넘긴다.

`NULL` 을 반환하는 대신에 `예외` 를 던지거나 `특수 사례 객체` 를 반환한다. 사용하려는 외부 API가 `NULL` 을 반환한다면 감싸기 메서드를 구현해 `예외` 를 던지거나 특수 사례 객체를 반환하는 방식을 고려한다.



```java
	/* BAD */

  public void registerItem(Item item) {
    if (item != null) {
      // persistentStore 객체가 NULL이 아니라고 보장할 수 있는가?
      ItemRegistry registry = peristentStore.getItemRegistry(); 
      if (registry != null) {
        Item existing = registry.getItem(item.getID());
        if (existing.getBillingPeriod().hasRetailOwner()) {
          existing.register(item);
        }
      }
    }
  }
```

```java
	/* Bad */
  List<Employee> employees = getEmployees();
  if (employees != null) {
    for(Employee e : employees) {
      totalPay += e.getPay();
    }
  }
```

```java
  /* Good */
  List<Employee> employees = getEmployees();
  for(Employee e : employees) {
    totalPay += e.getPay();
  }
  
  public List<Employee> getEmployees() {
    if( .. 직원이 없다면 .. )
      return Collections.emptyList();
    }
}
```

이렇게 코드를 변경하면 `NullPointerException` 이 발생할 가능성도 줄어든다.



```java
/* Bad */

calculator.xProjection(null, new Point(12, 13));

public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    return (p2.x – p1.x) * 1.5; // NullPointerException
  }
  ...
}
```

```java
/* Bad */

public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    if(p1 == null || p2 == null){
      throw InvalidArgumentException("Invalid argument for MetricsCalculator.xProjection");
    }
    return (p2.x – p1.x) * 1.5;
  }
```

이 방법의 경우 `NullPointerException` 은 발생하지 않지만, 이 함수를 호출한 상위 함수에서 `InvalidArgumentException` 을 처리해줘야만 한다.



```java
/* Bad */

public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    assert p1 != null : "p1 should not be null";
    assert p2 != null : "p2 should not be null";
    
    return (p2.x – p1.x) * 1.5;
  }
}
```

위의 예시보다는 좋은 사례이긴 하나, 근본적인 `NULL` 값을 전달해 생긴 근본적인 문제를 해결하지 못했다.



## 결론

깨끗한 코드는 읽기도 좋아햐 하지만 안정성도 높아야 한다. 오류 처리를 프로그램 논리와 분리해 독자적인 사안으로 고려하면 튼튼하고 깨끗한 코드를 작성할 수 있다. 오류 처리를 프로그램 논리와 분리하면 독립적인 추론이 가능해지며 코드 유지보수성도 크게 높아진다.



## NULL을 전달하지 마라

메서드에서 `NULL` 을 반환하는 방식도 나쁘지만 메서드로 `NULL` 을 전달하는 방식은 더 나쁘다.



## 생각 정리

* 코드를 작성할 때 내가 임의로 `오류 코드` 를 정의하는 것 보다, `예외` 를 던질 수 있도록 코딩하도록 하자
* `try` 블록을 일종의 `트랜잭션` 이라고 생각하고 하나의 작업 단위를 처리하도록 만들자
  * 프로그램 상태를 일관성 있도록 유지하고 의도대로 동작하는지 확인하기 위해, `특정한 예외` 를 던질 수 있도록 코드를 작성하자
  * 하나의 특정한 예외에 대해 다른 예외가 발생하는 로직을 추가하지 않음으로써, 코드를 일관성 있게 유지 가능
    * 하나의 `try` 문 안에서 여러 예외가 발생하는 논리를 기술한다면, 일관성을 해치는 코드
* `확인된 예외` 가 초래하는 비용은 생각보다 어마어마 🤭
  * 예외가 발생하는 함수를 호출한 상위 함수들에 계속해서 `thorws` 를 붙여줘야 하기 때문에, 코드의 유지보수가 어려워진다.
* `미확인 예외` 즉 `컴파일 타임` 에 일어나는 예외 처리보다 `런타임` 에 일어나는 예외를 잡을 수 있도록 코드를 작성
  * NEXTREE.IO. [JAVA 예외 처리에 대한 작은 생각](https://www.nextree.co.kr/p3239/). 06 JAN 2021
*  `NULL` 을 반환하고, 호출자에서 반환된 값이  `NULL`  을 체크하도록 하는 방식의 프로그램을 사용해왔다.
  * `NullPointerException` 의 근원지를 찾기란 생각보다 쉽지 않았다.
  * 해결할 수 있는 방법
    * `NULL` 을 반환하는 대신에 `예외` 를 던지거나 `특수 사례 객체` 를 반환하도록 하자
    * `List` 의 경우 `NULL` 말고 `Empty List` 를 반환하도록 하자

* `NULL` 을 전달하고, `NULL` 을 반환하는 것에 익숙해 지지 말자!
  * 반환 받은 객체 또는 매개변수로 받은 객체가 당연히  `NULL` 은 아닐 것이라고 믿을 수 있도록 프로그래밍 하자